"""create ingredient dish tables

Revision ID: 55965f498052
Revises:
Create Date: 2026-08-23 22:00:37.959726

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55965f498052"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dishes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dishes")),
        sa.UniqueConstraint("name", name=op.f("uq_dishes_name")),
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("calories_kcal_per_100g", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("protein_g_per_100g", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("carb_g_per_100g", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("fat_g_per_100g", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.CheckConstraint(
            "calories_kcal_per_100g >= 0", name=op.f("ck_ingredients_check_calories_non_negative")
        ),
        sa.CheckConstraint(
            "carb_g_per_100g >= 0", name=op.f("ck_ingredients_check_carb_non_negative")
        ),
        sa.CheckConstraint(
            "fat_g_per_100g >= 0", name=op.f("ck_ingredients_check_fat_non_negative")
        ),
        sa.CheckConstraint(
            "protein_g_per_100g >= 0", name=op.f("ck_ingredients_check_protein_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingredients")),
        sa.UniqueConstraint("name", name=op.f("uq_ingredients_name")),
    )
    op.create_table(
        "dish_ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dish_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("quantity_g", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.CheckConstraint(
            "quantity_g > 0", name=op.f("ck_dish_ingredients_check_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["dish_id"], ["dishes.id"], name=op.f("fk_dish_ingredients_dish_id_dishes")
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            name=op.f("fk_dish_ingredients_ingredient_id_ingredients"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dish_ingredients")),
        sa.UniqueConstraint("dish_id", "ingredient_id", name="uq_dish_ingredient"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dish_ingredients")
    op.drop_table("ingredients")
    op.drop_table("dishes")
    # ### end Alembic commands ###
