"""add global constant table

Revision ID: 61e021f47bdb
Revises: e2f5bd74fff4
Create Date: 2026-08-29 19:46:52.914964

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61e021f47bdb"
down_revision: str | Sequence[str] | None = "924ed0cf9155"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_constants",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("current_usda_food_page", sa.Integer(), nullable=False),
        sa.CheckConstraint("id=1", name=op.f("ck_global_constants_singleton_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_global_constants")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("global_constants")
    # ### end Alembic commands ###
