"""add fdc id to ingredient

Revision ID: 924ed0cf9155
Revises: 55965f498052
Create Date: 2026-08-24 17:24:14.489914

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "924ed0cf9155"
down_revision: str | Sequence[str] | None = "55965f498052"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingredients", sa.Column("fdc_id", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("uq_ingredients_name"), "ingredients", type_="unique")
    op.create_unique_constraint(op.f("uq_ingredients_fdc_id"), "ingredients", ["fdc_id"])
    op.create_check_constraint(
        op.f("ck_ingredients_check_fdc_id_non_negative"), "ingredients", "fdc_id >= 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_ingredients_check_fdc_id_non_negative"), "ingredients", type_="check"
    )
    op.drop_constraint(op.f("uq_ingredients_fdc_id"), "ingredients", type_="unique")
    op.create_unique_constraint(
        op.f("uq_ingredients_name"), "ingredients", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("ingredients", "fdc_id")
    # ### end Alembic commands ###
